services:
  s1admin:
    image: dpage/pgadmin4:latest
    container_name: 68-s1-admin
    ports:
      - ${AD_PORT}:3332
    environment:
      PGADMIN_DEFAULT_EMAIL: ${AD_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${AD_PASS}