services:
  s1db:
    image: postgres:latest
    container_name: 68-s1-database
    ports:
    - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}